org: gplopes29
app: serverless
service: serverless

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

- name: Label Regex
  uses: Bhacaz/label-regex@v1
  
functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
      - http:
          path: /:id
          method: ANY
      - http:
          path: /cadastraUsuario
          method: POST
      - http:
          path: /alteraUsuario
          method: PUT
      - http:
          path: /deleteUsuario/:id
          method: DELETE
plugins:
  - serverless-offline
